# Generated by Django 5.0.3 on 2024-04-24 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.RegexValidator(regex='^[а-яА-я]+$')], verbose_name='Направление (Например, ИВТб)')),
                ('course', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('Teacher', 'Преподаватель'), ('Student', 'Студент')], max_length=7, verbose_name='Должность')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администрирование')),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.thread', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
