# Generated by Django 5.0.3 on 2024-04-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='identifier',
            field=models.IntegerField(null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.thread', verbose_name='Поток'),
        ),
    ]
